version: '3.5'

services:
  telegram-download-daemon:
    #build: .
    image: alfem/telegram-download-daemon:latest
    container_name: telegram-download
    read_only: true
    environment:
      TELEGRAM_DAEMON_API_ID: "YOUR API ID HERE"
      TELEGRAM_DAEMON_API_HASH: "YOUR API HASH HERE"
      TELEGRAM_DAEMON_CHANNEL: "YOUR CHANNEL ID HERE"
      TELEGRAM_DAEMON_DEST: "/downloads"
      TELEGRAM_DAEMON_SESSION_PATH: "/session"
      #TELEGRAM_DAEMON_WORKERS: 2
      # 代理配置 (可选)
      TELEGRAM_DAEMON_PROXY_TYPE: ""
      TELEGRAM_DAEMON_PROXY_ADDR: ""
      TELEGRAM_DAEMON_PROXY_PORT: ""
      TELEGRAM_DAEMON_PROXY_USERNAME: ""
      TELEGRAM_DAEMON_PROXY_PASSWORD: ""
      TELEGRAM_DAEMON_PROXY_SECRET: ""
    volumes:
       - downloads:/downloads
       - sessions:/session
    restart: unless-stopped

volumes:
    downloads:
    sessions:
